name: Deploy
on: 
  deployment

jobs:
  configure:
    name: Configure Tyk.conf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find and Replace
        uses: shitiomatic/str-replace@master
        with:
          find: '@@API_TAGS@@'
          replace: '["preview", "staging", "release", "demo"]'
          include: 'tyk.conf'
      - name: Build
        run: docker build . --file Dockerfile --tag registry.heroku.com/earnnest-gateway-dev/web
      - name: Heroku Login
        run: docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL}}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
      - name: Heroku Push
        run: heroku container:push web --app earnnest-gateway-dev
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
      - name: Heroku Release
        run: heroku container:release web --app earnnest-gateway-dev
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
